"use client";

import Link from "next/link";
import { useActionState, useState } from "react";
import { createCapsule, type CapsuleActionState } from "@/app/dashboard/actions";

const choices = [{ label: "1 month", days: 30 }, { label: "3 months", days: 90 }, { label: "6 months", days: 180 }, { label: "1 year", days: 365 }, { label: "5 years", days: 1825 }];
const initialState: CapsuleActionState = { ok: false };
function future(days: number) { const date = new Date(); date.setDate(date.getDate() + days); return date.toISOString(); }

export function CapsuleForm() {
  const [state, action, pending] = useActionState(createCapsule, initialState);
  const [date, setDate] = useState(future(365));
  if (state.ok && state.id) return <div className="success-state"><p className="eyebrow">Sealed successfully</p><h2>Capsule sealed.</h2><p>Opens {new Date(state.unlockAt || date).toLocaleDateString(undefined, { dateStyle: "long" })}.</p><Link className="button" href={`/dashboard/${state.id}`}>View Capsule <span>↗</span></Link></div>;
  const choose = (days: number) => setDate(future(days));
  return <form action={action} aria-busy={pending}><div className="field"><label htmlFor="title">Title</label><input id="title" name="title" placeholder="Open this when I&apos;m 30" maxLength={160} required disabled={pending} /></div><div className="field"><label htmlFor="message">Your message</label><textarea id="message" name="message" placeholder="What do you want your future self to remember?" maxLength={100000} required disabled={pending} /></div><div className="field"><label htmlFor="unlock-date">Open in</label><div className="date-options">{choices.map((choice) => <button key={choice.days} className={`date-option ${Math.abs(new Date(date).getTime() - Date.now() - choice.days * 86400000) < 86400000 ? "active" : ""}`} type="button" onClick={() => choose(choice.days)} disabled={pending}>{choice.label}</button>)}</div><input id="unlock-date" className="field" type="datetime-local" value={date.slice(0,16)} onChange={(event) => { const next = new Date(event.target.value); if (!Number.isNaN(next.getTime())) setDate(next.toISOString()); }} aria-label="Custom opening date" disabled={pending} /><input type="hidden" name="unlockAt" value={date} /><p className="subtle">🔒 Sealed until {new Date(date).toLocaleDateString(undefined, { dateStyle: "long" })}</p></div><div className="inline-fields"><div className="field"><label htmlFor="projectName">Project name <span className="subtle">(optional)</span></label><input id="projectName" name="projectName" disabled={pending} /></div><div className="field"><label htmlFor="websiteUrl">Website URL <span className="subtle">(optional)</span></label><input id="websiteUrl" name="websiteUrl" type="url" placeholder="https://" disabled={pending} /></div></div><div className="field"><label htmlFor="githubUrl">GitHub URL <span className="subtle">(optional)</span></label><input id="githubUrl" name="githubUrl" type="url" placeholder="https://github.com/" disabled={pending} /></div><div className="field"><label htmlFor="additionalNotes">Additional notes <span className="subtle">(optional)</span></label><textarea id="additionalNotes" name="additionalNotes" rows={4} disabled={pending} /></div>{state.error && <p className="form-error" role="alert">{state.error}</p>}<button className="button" type="submit" disabled={pending}>{pending ? "Creating Capsule..." : "Seal this capsule"} {!pending && <span>↗</span>}</button></form>;
}
